### ISSUE TITLE
[Angular]: CamelizePipe for Angular Package

### ISSUE THREAD

**Issue by ruslanguns** [ruslanguns/ruso-monorepo#57]
## Feature Request

We need a CamelizePipe for our common angular library, this should camelize a sentense, deleting special chars, accepting latin chars as well.

## Is your feature request related to a problem? Please describe.
No

### should camelize sentence

From: Configurar YARN en tus proyectos de ANGULAR
To: configurarYarnEnTusProyectosDeAngular

### should camelize special strings

From: http://example.com/foo
To: httpExampleComFoo

### should camelize text with Latin Chars

From: El éxito se mide por tus hechos y no por tus palabras
To: elExitoSeMidePorTusHechosYNoPorTusPalabras

This feature should be pulled following the [Contributors guideliness](https://github.com/ruslanguns/ruso-monorepo/blob/master/CONTRIBUTING.md), as well should cover full test coverage, otherwise it wont be accepted.

**Comment by harshilparmar** [comment]
@ruslanguns  My approach for this problem is

1. loop through string
2. if it is not special character  continue or delete that char
3 Make first latter uppercase after space
What you think ?
I don't know what to do for Latin chars? i18next?
